[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = AR
ST = Buenos Aires
L = CABA
O = Drawers
OU = IT
CN = drawers.docker

[v3_req]
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = drawers.docker
DNS.2 = *.drawers.docker
DNS.3 = localhost
IP.1 = 127.0.0.1
IP.2 = 172.21.5.5
